[package]
name = "nk"
version = "0.6.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = "0.5.0"
const_format = "0.2.26"
indoc = "1.0.7"
shellexpand = "2.1.2"
serde = { version = "1.0.145", features = ["derive"] }
serde_yaml = "0.9.13"
regex = "1.6.0"
serde_with = "2.0.1"
rhai = { version = "1.10.1", features = [
    "no_closure",
    "no_custom_syntax",
    "serde",
] }
hostname = "0.3.1"
serde_json = "1.0.85"
console = "0.15.2"
textwrap = "0.15.1"
