# https://numtide.github.io/devshell
[devshell]
motd = ""
packages = [
    # nix
    "nixpkgs-fmt",
    # rust
    "rustup",
    # release
    "gh",
    "semver-tool",
    "jq",
]

[[env]]
name = "PATH"
prefix = "${PRJ_ROOT}/.cargo/bin"

# TODO: may want to check if these things are setup first... (or find some other way to make them quiet)
[devshell.startup.rust]
text = """
rustup default stable
rustup component add rust-src
# TODO: maybe set install.root in the config (.cargo/config.toml) instead of specifying this here. https://doc.rust-lang.org/cargo/commands/cargo-install.html#description
cargo install --root ./.cargo --quiet cargo-edit
"""

[devshell.startup.git-hooks]
text = "git config --local core.hookspath .hooks"
