# https://numtide.github.io/devshell
[devshell]
motd = ""
packages = [
    # nix
    "nixpkgs-fmt",
    # rust
    "rustup",
    # release
    "gh",
    "semver-tool",
    "jq",
]

[devshell.startup.git-hooks]
text = "git config --local core.hookspath .hooks"
