# https://numtide.github.io/devshell
[devshell]
motd = ""
packages = [
    # nix
    "nixpkgs-fmt",
    # rust
    "rustup",
    # release
    "gh",
    "semver-tool",
    "jq",
]

# TODO: may want to check if these things are setup first... (or find some other way to make them quiet)
[devshell.startup.rust]
text = """
rustup default stable
rustup component add rust-src
cargo install cargo-edit --quiet
"""

[devshell.startup.git-hooks]
text = "git config --local core.hookspath .hooks"
