[target.'cfg(target_env = "msvc")']
rustflags = ["-C", "target-feature=+crt-static"]

[target.'cfg(target_env = "musl")']
rustflags = [
    "-C",
    "target-feature=+crt-static",
    "-L",
    "-Wl,--copy-dt-needed-entries",
]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"
