name: build
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: Build
    strategy:
      matrix:
        build:
          - artifact: nk-macos-x86_64
            target: x86_64-apple-darwin
            os: macos-latest
          - artifact: nk-macos-aarch64
            target: aarch64-apple-darwin
            os: macos-latest
          - artifact: nk-linux-x86_64
            target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - artifact: nk-windows-x86_64.exe
            target: x86_64-pc-windows-msvc
            os: windows-latest
          - artifact: nk-windows-aarch64.exe
            target: aarch64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install target
        run: rustup target add ${{ matrix.build.target }}
      - name: Setup musl
        run: sudo apt-get install -y musl-tools
        if: endsWith(matrix.build.target, '-musl')
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --target ${{ matrix.build.target }}
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build.artifact }}
          path: target/${{ matrix.build.target }}/release/${{ runner.os == 'Windows' && 'nk.exe' || 'nk' }}
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create Release
        env:
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir assets

          # move binaries to assets directory
          for path in artifacts/*; do
            declare artifact="$(basename "$path")"
            mv "${path}/nk"* "assets/${artifact}"
          done

          # create release
          gh release create \
            --title "$GITHUB_REF_NAME" \
            --notes '' \
            "$GITHUB_REF_NAME" \
            "assets/"*
