name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    strategy:
      matrix:
        build:
          - os: ubuntu-latest
            path: target/release/nk
            artifact: nk-linux-x86_64
          - os: windows-latest
            path: target/release/nk.exe
            artifact: nk-windows-x86_64.exe
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Wait for validate job to finish
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          check-name: Validate
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        # TODO: ugh, why is this broken?
        if: ${{ matrix.build.os != 'windows-latest' }}
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Upload binary
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.build.artifact }}
          path: ${{ matrix.build.path }}
