name: build
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: Build
    strategy:
      matrix:
        build:
          - os: macos-latest
            path: target/release/nk
            artifact: nk-macos-x86_64
          - os: ubuntu-latest
            path: target/x86_64-unknown-linux-gnu/release/nk
            artifact: nk-linux-x86_64
          - os: windows-latest
            path: target/release/nk.exe
            artifact: nk-windows-x86_64.exe
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release
        if: runner.os != 'Linux'
      - name: Build
        env:
          LDFLAGS: -Wl,--copy-dt-needed-entries
          RUSTFLAGS: -C target-feature=+crt-static
        run: cargo build --release --target x86_64-unknown-linux-gnu
        if: runner.os == 'Linux'
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.build.artifact }}
          path: ${{ matrix.build.path }}
