name: build
on:
  workflow_dispatch: # Manually trigger
  push:
    tags:
      - v*
jobs:
  build:
    name: Build
    strategy:
      matrix:
        build:
          - os: macos-latest
            path: target/release/nk
            artifact: nk-macos-x86_64
          # TODO: stable-aarch64-apple-darwin
          - os: ubuntu-latest
            path: target/x86_64-unknown-linux-musl/release/nk
            artifact: nk-linux-x86_64
          - os: windows-latest
            path: target/release/nk.exe
            artifact: nk-windows-x86_64.exe
          # TODO: aarch64-pc-windows-msvc
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup musl
        run: |
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get install -y musl-tools
        if: runner.os == 'Linux'
      - name: Build # Linux
        env:
          LDFLAGS: -Wl,--copy-dt-needed-entries
          RUSTFLAGS: -C target-feature=+crt-static
        run: cargo build --release --target x86_64-unknown-linux-musl
        if: runner.os == 'Linux'
      - name: Build
        run: cargo build --release
        if: runner.os != 'Linux'
      - name: Print version
        run: ${{ matrix.build.path }} version
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.build.artifact }}
          path: ${{ matrix.build.path }}
