name: release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      # TODO: maybe split these back out, we likely don't need them to run on every os
      - name: Lint
        run: cargo clippy --quiet
      - name: Style Check
        run: rustfmt src/**/*.rs src/*.rs --check
      - name: Build
        run: cargo build --release
      # TODO: remove
      - name: TEMP DEBUG
        run: |
          find . -type f
      # TODO: since we can't compile macos arm yet, we'll have to attach this as an artifact, download, and create the release locally
      # - name: Upload binary
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: nk
      #     # path: # TODO: path to binary
