name: validate
on: push
jobs:
  validate:
    name: Validate
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: cargo clippy --quiet
      - name: Style Check
        run: cargo fmt --check
