name: validate
on:
  push:
    branches:
      - "**"
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: cargo clippy --quiet
      - name: Style Check
        run: cargo fmt --check
